# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Mislav Javor"

author:
  facebook:         micojavor
  twitter:          mislavcodes
  github:           mislavjavor
  linkedin:         mislavjavor
  email:            mislav.javor@outlook.com

copyright:
  year:             2017
  name:             Mislav Javor

# Google-analytics
google-analytics:
  id:               "UA-91385022-1"

# Disqus
disqus:
  id:               "mislavjavor"

# URL
url:                "mislavjavor.com" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/Zagreb
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           20
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "My Projects"
    url:            "/my_projects"
  - name:           "Github"
    url:            "https://github.com/mislavjavor"


# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]
